import { test, expect } from '@playwright/test';

test.describe('Print Flow', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test('loads app with theme selector', async ({ page }) => {
    // Wait for theme selector to load themes
    await expect(page.locator('theme-selector')).toBeVisible();
    
    // Check that print button exists
    await expect(page.locator('#print-btn')).toBeVisible();
  });

  test('shows cards automatically when theme loads', async ({ page }) => {
    // Wait for cards to appear (auto-loaded with first theme)
    await page.waitForSelector('#print-btn:not([disabled])');
    
    // Check that card-grid contains cards
    const cardGrid = page.locator('card-grid');
    await expect(cardGrid).toBeVisible();
    
    // Verify cards were generated by checking shadow DOM
    const cardCount = await cardGrid.evaluate((el) => {
      const shadowRoot = el.shadowRoot;
      if (!shadowRoot) return 0;
      return shadowRoot.querySelectorAll('charade-card').length;
    });
    
    // Should show all 24 cards from animals theme
    expect(cardCount).toBe(24);
  });

  test('enables print button after cards load', async ({ page }) => {
    // Wait for print button to be enabled (indicates cards loaded)
    await page.waitForSelector('#print-btn:not([disabled])');
    
    // Print button should be enabled
    await expect(page.locator('#print-btn')).toBeEnabled();
  });

  test('displays cards in print media', async ({ page }) => {
    // Wait for cards to load
    await page.waitForSelector('#print-btn:not([disabled])');
    
    // Verify cards exist before switching to print
    const cardGrid = page.locator('card-grid');
    const cardCount = await cardGrid.evaluate((el) => {
      const shadowRoot = el.shadowRoot;
      return shadowRoot?.querySelectorAll('charade-card').length || 0;
    });
    expect(cardCount).toBe(24);
    
    // Emulate print media
    await page.emulateMedia({ media: 'print' });
    
    // Card grid should still be visible
    await expect(cardGrid).toBeVisible();
    
    // Theme selector should be hidden in print
    const themeContainer = page.locator('#theme-container');
    await expect(themeContainer).toBeHidden();
  });
});
